name: Setup COBOL

on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fabasoad/setup-cobol-action@v1
      - name: Run script
        run: |
          cobc -x helloworld.cob
          ./helloworld
