name: Build

on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fabasoad/setup-cobol-action@v1
      - uses: actions/cache@v4
        with: 
          path: /usr/bin/cobc
          
      - name: Run script
        run: |
          cobc -x helloworld.cob
          ./helloworld
