name: Build

on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - uses: fabasoad/setup-cobol-action@v1

      - uses: actions/cache@v4
        with: 
          fail-on-cache-miss: false
          path: /usr/bin/
          key: ${{ runner.os }}-cobc-${{ hashFiles('cobc') }}

        if: steps.cache.outputs.cache-hit != 'true'
        uses: fabasoad/setup-cobol-action@v1

          
          
      - name: Run script
        run: |
          cobc -x helloworld.cob
          ./helloworld
